os: linux
dist: bionic
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - openmpi-bin
      - libnuma-dev
      - libopenmpi-dev
language: cpp

before_install:
  - cd tests
  - wget https://github.com/google/googletest/archive/release-1.10.0.zip
  - unzip release-1.10.0.zip
  - mv googletest-release-1.10.0 gtest-1.7.0    # FIXME PLEASE AS IN #40
  - cd ..

before_script:
  - mkdir build && cd build
  - cmake -DARGO_BACKEND_MPI=ON -DARGO_BACKEND_SINGLENODE=ON -DARGO_TESTS=ON -DBUILD_DOCUMENTATION=ON -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_C_COMPILER=mpicc ../
  - make

script:
  - make test
